/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/**/*.{js,jsx,ts,tsx,md,mdx}",
    "./docs/**/*.{md,mdx}",
    "./docusaurus.config.{js,ts}",
    "./src/theme/**/*.{js,jsx,ts,tsx}",
    'node_modules/flowbite-react/lib/esm/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        // Design System Colors using OKLCH
        background: 'oklch(var(--background))',
        foreground: 'oklch(var(--foreground))',
        card: {
          DEFAULT: 'oklch(var(--card))',
          foreground: 'oklch(var(--card-foreground))',
        },
        popover: {
          DEFAULT: '#ffffff',
          foreground: '#0f172a',
        },
        primary: {
          DEFAULT: 'oklch(var(--primary))',
          foreground: 'oklch(var(--primary-foreground))',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        secondary: {
          DEFAULT: '#6b7280',
          foreground: '#ffffff',
        },
        muted: {
          DEFAULT: '#f9fafb',
          foreground: '#6b7280',
        },
        accent: {
          DEFAULT: '#f3f4f6',
          foreground: '#111827',
        },
        destructive: {
          DEFAULT: '#ef4444',
          foreground: '#ffffff',
        },
        border: '#e5e7eb',
        input: '#d1d5db',
        ring: '#3b82f6',
        chart: {
          1: '#3b82f6',
          2: '#ef4444',
          3: '#22c55e',
          4: '#f59e0b',
          5: '#8b5cf6',
        },
        sidebar: {
          DEFAULT: '#f8fafc',
          foreground: '#0f172a',
          primary: '#3b82f6',
          'primary-foreground': '#ffffff',
          accent: '#f1f5f9',
          'accent-foreground': '#0f172a',
          border: '#e2e8f0',
          ring: '#3b82f6',
        },
        // Brand Colors
        brand: {
          blue: '#2563eb',
          'blue-dark': '#1d4ed8',
          'blue-light': '#3b82f6',
        },
        gray: {
          "950": "#151D28",
          "900": "#111928",
          "800": "#1F2A37",
          "700": "#374151",
          "600": "#4B5563",
          "500": "#6B7280",
          "400": "#9CA3AF",
          "300": "#D1D5DB",
          "200": "#E5E7EB",
          "100": "#F3F4F6",
          "50": "#F9FAFB",
        },
        red: {
          "900": "#771D1D",
          "800": "#9B1C1C",
          "700": "#C81E1E",
          "600": "#E02424",
          "500": "#F05252",
          "400": "#F98080",
          "300": "#F8B4B4",
          "200": "#FBD5D5",
          "100": "#FDE8E8",
          "50": "#FDF2F2",
        },
        orange: {
          "900": "#771D1D",
          "800": "#8A2C0D",
          "700": "#B43403",
          "600": "#D03801",
          "500": "#FF5A1F",
          "400": "#FF8A4C",
          "300": "#FDBA8C",
          "200": "#FCD9BD",
          "100": "#FEECDC",
          "50": "#FFF8F1",
        },
        yellow: {
          "900": "#633112",
          "800": "#723B13",
          "700": "#8E4B10",
          "600": "#9F580A",
          "500": "#C27803",
          "400": "#E3A008",
          "300": "#FACA15",
          "200": "#FCE96A",
          "100": "#FDF6B2",
          "50": "#FDFDEA",
        },
        green: {
          "900": "#014737",
          "800": "#03543F",
          "700": "#046C4E",
          "600": "#057A55",
          "500": "#0E9F6E",
          "400": "#31C48D",
          "300": "#84E1BC",
          "200": "#BCF0DA",
          "100": "#DEF7EC",
          "50": "#F3FAF7",
        },
        teal: {
          "900": "#014451",
          "800": "#05505C",
          "700": "#036672",
          "600": "#047481",
          "500": "#0694A2",
          "400": "#16BDCA",
          "300": "#7EDCE2",
          "200": "#AFECEF",
          "100": "#D5F5F6",
          "50": "#EDFAFA",
        },
        indigo: {
          "900": "#362F78",
          "800": "#42389D",
          "700": "#5145CD",
          "600": "#5850EC",
          "500": "#6875F5",
          "400": "#8DA2FB",
          "300": "#B4C6FC",
          "200": "#CDDBFE",
          "100": "#E5EDFF",
          "50": "#F0F5FF",
        },
        purple: {
          "900": "#4A1D96",
          "800": "#5521B5",
          "700": "#6C2BD9",
          "600": "#7E3AF2",
          "500": "#9061F9",
          "400": "#AC94FA",
          "300": "#CABFFD",
          "200": "#DCD7FE",
          "100": "#EDEBFE",
          "50": "#F6F5FF",
        },
        pink: {
          "900": "#751A3D",
          "800": "#99154B",
          "700": "#BF125D",
          "600": "#D61F69",
          "500": "#E74694",
          "400": "#F17EB8",
          "300": "#F8B4D9",
          "200": "#FAD1E8",
          "100": "#FCE8F3",
          "50": "#FDF2F8",
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'calc(var(--radius) + 4px)',
      },
      fontFamily: {
        sans: [
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        mono: [
          '"Fira Code"',
          '"JetBrains Mono"',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-up': 'fadeUp 0.5s ease-out',
        'fade-down': 'fadeDown 0.5s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'bounce-gentle': 'bounceGentle 2s infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeDown: {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
      },
      boxShadow: {
        'xs': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'glow': '0 0 20px rgb(37 99 235 / 0.15)',
        'glow-lg': '0 0 40px rgb(37 99 235 / 0.25)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-primary': 'linear-gradient(135deg, #2563eb 0%, #3b82f6 100%)',
        'gradient-secondary': 'linear-gradient(135deg, #64748b 0%, #94a3b8 100%)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
    fontWeight: {
      thin: "100",
      "extra-light": "200",
      light: "300",
      regular: "400",
      medium: "500",
      semibold: "600",
      "semi-bold": "600",
      bold: "700",
      "extra-bold": "800",
      black: "900",
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.215rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "3.75rem",
      "7xl": "4.5rem",
      "8xl": "6rem",
      "9xl": "8rem",
    },
  },
  plugins: [
    require('flowbite/plugin'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    // Custom plugin for design system utilities
    function({ addUtilities, addComponents, theme }) {
      addUtilities({
        '.text-balance': {
          'text-wrap': 'balance',
        },
        '.text-pretty': {
          'text-wrap': 'pretty',
        },
      })

      addComponents({
        '.btn': {
          '@apply inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none': {},
        },
        '.btn-primary': {
          '@apply bg-primary text-primary-foreground': {},
        },
        '.btn-secondary': {
          '@apply bg-secondary text-secondary-foreground hover:bg-secondary/80': {},
        },
        '.btn-outline': {
          '@apply border border-input bg-background hover:bg-accent hover:text-accent-foreground': {},
        },
        '.btn-ghost': {
          '@apply hover:bg-accent hover:text-accent-foreground': {},
        },
        '.card': {
          '@apply rounded-lg border bg-card text-card-foreground shadow-sm': {},
        },
        '.input': {
          '@apply flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50': {},
        },
      })
    },
  ],
  corePlugins: {
    preflight: false,
  },
};
